os: Visual Studio 2015

platform:
    - Win32
    - x64

environment:
    matrix:
        - RUST: 1.14.0
          ABI: msvc
        - RUST: 1.14.0
          ABI: gnu
        - RUST: 1.19.0
          ABI: msvc
        - RUST: 1.19.0
          ABI: gnu
        - RUST: stable
          ABI: msvc
        - RUST: stable
          ABI: gnu
        - RUST: beta
          ABI: msvc
        - RUST: beta
          ABI: gnu
        - RUST: nightly
          ABI: msvc
        - RUST: nightly
          ABI: gnu

cache:
    - rust -> appveyor.*
    - target -> Cargo.toml
    - '%USERPROFILE%\.cargo'

build_script: appveyor.bat

